### ISSUE TITLE
dict conversion with self reference

### ISSUE THREAD

**Issue by alvinshaita** [alvinshaita/attridict#12]
While creating a self reference with attridict works fine, creating an attridict object from a dict with self referencing raises a `RecursionError`
This happens when `deep=True`, which is the default behavior

```
>>> a = {}
>>> a
{}
>>> a["me"] = a
>>> a
{'me': {...}}

>>> import attridict
>>> attridict(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alvin/.local/lib/python3.10/site-packages/attridict.py", line 26, in __init__
    self.__to_attridict(data, deep)
  File "/home/alvin/.local/lib/python3.10/site-packages/attridict.py", line 111, in __to_attridict
    self.__dict__[key] = type(self)(value, deep)
    ....
    ....
  File "/home/alvin/.local/lib/python3.10/site-packages/attridict.py", line 26, in __init__
    self.__to_attridict(data, deep)
  File "/home/alvin/.local/lib/python3.10/site-packages/attridict.py", line 111, in __to_attridict
    self.__dict__[key] = type(self)(value, deep)
  File "/home/alvin/.local/lib/python3.10/site-packages/attridict.py", line 18, in __init__
    verified_dict = self.__type_verification(data)
  File "/home/alvin/.local/lib/python3.10/site-packages/attridict.py", line 152, in __type_verification
    if type(data) != dict or type(data) != AttriDict:
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by alvinshaita** [comment]
Solved: https://github.com/alvinshaita/attridict/pull/13

**Comment by alvinshaita** [comment]
Solved: https://github.com/alvinshaita/attridict/pull/13
